version: '3.0'
services:
  postgres:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    restart: 'always'
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test_db
  rest-app:
    build: rest_app
    ports:
      - "3000:3000"
    restart: 'always'

