name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup PostgreSQL
      run: cd postgres/ ; docker-compose up -d
    - name: Install dependencies
      run: cd rest_app/ ;lein deps
    - name: build
      run: cd rest_app/ ;lein uberjar
      env:
        DBTYPE: postgresql
        DBNAME: test_db
        DBHOST: localhost
        DBUSER: test
        DBPASSWORD: test
    - name: Run tests
      run: cd rest_app/ ;lein test
      env:
        DBTYPE: postgresql
        DBNAME: test_db
        DBHOST: localhost
        DBUSER: test
        DBPASSWORD: test
