name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup PostgreSQL
      uses: actions/checkout@v2
      with:
        # Version of PostgreSQL to use
        postgresql version: latest # optional, default is latest
        # POSTGRES_DB - name for the default database that is created
        postgresql db: test_db # optional, default is 
        # POSTGRES_USER - create the specified user with superuser power
        postgresql user: test # optional, default is 
        # POSTGRES_PASSWORD - superuser password
        postgresql password: test # optional, default is
    - name: Install dependencies
      run: cd rest_app/ ;lein deps
    - name: build
      run: cd rest_app/ ;lein uberjar
    #- name: Run tests
    #  run: lein test
