name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run docker-compose
    - name: Install dependencies
      run: lein deps
    - name: build
      run: lein uberjar
    #- name: Run tests
    #  run: lein test
